### ISSUE TITLE
is getirrsubsystem correct?

### ISSUE THREAD

**Issue by kalmarek** [kalmarek/KnuthBendix.jl#18]
As implemented here:
https://github.com/kalmarek/KnuthBendix.jl/blob/342b15ef14e9ad1f0c437e94baea7308c08dd0f6/src/kbs1.jl#L43
shouldn't we test all subwords, not only prefixes and suffixes?

btw. rewriting and comparing a word is a poor test for irreducibility. This could be implemented e.g.
```julia
function isirreducible(w::AbstractWord, rws::RewritingSystem)
    for (lhs, _) in rules(rws)
        issubword(lhs, w) && lhs != w && return false
    end
    return true
end
```
without allocations

**Comment by mikolajpabiszczak** [comment]
Aren't we testing all subwords? 

Here we first check prefixes:
https://github.com/kalmarek/KnuthBendix.jl/blob/342b15ef14e9ad1f0c437e94baea7308c08dd0f6/src/kbs1.jl#L49-L53

But here I check everything else (there are two for-loops):
https://github.com/kalmarek/KnuthBendix.jl/blob/342b15ef14e9ad1f0c437e94baea7308c08dd0f6/src/kbs1.jl#L54-L60

(Two separate loops in order to ensure that I check only proper subwords).

As to the rest of the issue: absolutely right, will fix that.

**Comment by kalmarek** [comment]
very well, i must have missed the inner loop!
